import "@/app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-text">
        <div className="mb-20">{children}</div>
      </body>
    </html>
  );
}
